name: Terraform Syntax Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Terraform environment
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.6

      - name: Initialize Terraform
        run: terraform init -backend=false

      - name: Validate Terraform configuration
        run: terraform validate